name: 'Terraform Apply'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    terraform:
      name: "Terraform Apply"
      runs-on: ubuntu-latest
      env:
        TF_CLOUD_ORGANIZATION: "yurehn_corp_inc"
        TF_WORKSPACE: "Build_Front_Web"
        TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

      steps:
        - name: Checkout
          uses: actions/checkout@v4
        
        - name: Upload Configuration
          uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.2.0
          id: apply-upload
          with:
            workspace: ${{ env.TF_WORKSPACE }}
            directory: "./"
        
        - name: Create Apply run
          uses: hashicorp/tfc-workflows-github/actions/create-run@v1.2.0
          id: apply-run
          with: 
            workspace: ${{ env.TF_WORKSPACE }}
            configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

        - name: Apply
          uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.2.0
          if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
          id: apply-ouput
          with:
            run: ${{ steps.apply-run.outputs.run_id }}
            comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"

        - name: Save VM IP to Google Cloud Storage
          run: |
            terraform init
            VM_IP=$(terraform output -json machine_ips | jq -r '.["virtual-machine-pokeapi"]')
            echo $VM_IP > vm_ip.txt
            gsutil cp vm_ip.txt gs://poke_api/vm_ips/${{ secrets.WORKSPACE }}.txt
          env:
            GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
